outbox-adr [add] outbox adr file
drim-dev/drimstarter pull request #15
Opened 2024-09-17 14:01 UTC by AssetOtinchiev

2024-09-18 07:50 UTC, mitro requested changes

2024-09-18 07:50 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +## Considered Options
The ADR structure differs a bit from the chosen MADR 4.0.0 format. You can look at https://github.com/drim-dev/drimstarter/blob/develop/documents/adrs/backend/0001-grpc-communication.md and use it as an example

2024-09-18 07:50 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +### Option 3: **Event-Driven Architecture with Message Queues**
Do you propose using Transactional Outbox instead of RabbitMQ or Kafka? This is a new idea for me; I never considered it. It is clever because we can eliminate separate queueing systems, thus reducing the system's complexity.

But I think you should add one more fact to the section "Context and Problem Statement." One of Drimstarter's goals is to be a training system for developers. Queues are an essential topic to learn, so we should use them :) We could use Transactional Outbox exclusively for some cases, but for some, it should be Transactional Outbox + RabbotMQ and Transactional Outbox + Kafka. This ADR should specify this context so others can understand the architectural details.

2024-09-18 17:58 UTC, AssetOtinchiev commented
@mitro I've updated file, you can check it

2024-09-19 04:38 UTC, mitro requested changes

2024-09-19 04:38 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +* Offers exactly-once message delivery semantics in combination with a transactional outbox pattern, providing robust reliability guarantees.
It is not true. Transactional outbox does not provide exactly-once semantics. It provides at-least-once semantics, because it uses retries. Moreover, processing semantics are defined not only on the publisher side but also on the consumer side. So, let's delete this point.

2024-09-19 04:38 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +In developing a backend for a crowdfunding platform Drimstarter, the need for reliable, scalable, and fault-tolerant message delivery in asynchronous communication between microservices has emerged.
Could you document here that we are developing a training system for developers and prefer to use more tools over simplicity?

2024-09-19 04:38 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +* **Developer Productivity**: The approach should be straightforward to implement, test, and maintain in a distributed microservices environment.
I propose to add a point:

* **Developer Training**: The solution should use message queues to train developers on their usage.

2024-09-19 04:38 UTC, mitro commented on documents/adrs/backend/0002-outbox-communication.md
> +### Transactional Outbox with RabbitMQ
It still doesn't follow the MADR 4.0.0 format. The "Considered Options" section should contain a list of options without pros and cons. There is a separate section, "Pros and Cons of the Options," where the pros and cons should go. Please see https://github.com/drim-dev/drimstarter/blob/features/outbox-adr/documents/adrs/backend/0001-grpc-communication.md#pros-and-cons-of-the-options

2024-09-29 13:24 UTC, AssetOtinchiev commented
@mitro i fixed your comments, you can check it

2024-09-30 11:38 UTC, mitro approved these changes

2024-10-01 04:19 UTC, merged