Issue 16: Get Deposit Address
drim-dev/drimstarter pull request #17
Opened 2024-09-19 07:15 UTC by Kydyralin

1. Added projects for BlockchainService
1. Added CryptoPayments feature
1. Added GetDepositAddress method

2024-10-07 12:56 UTC, mitro requested changes

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Program.cs
> +// TODO: uncomment after resolving problem with BlockchainService.Client generation
Should be deleted?

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Clients/BlockchainService/cryptopayments.proto
> +  string user = 1;
`userId`?

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +        private const string Path = "/cryptopayments";
I propose to use `/crypto-payments/addresses`

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Models/DepositAddressModel.cs
> +public record DepositAddressModel(string AddressId);
Let's use just `Address`. We should return a full Bitcoin address, not its id.

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +                return TypedResults.Created($"{Path}/{depositAddress.AddressId}", depositAddress);
`HTTP 201 Created` is usually returned on POST requests. On a GET request we should return `HTTP 200 OK`

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +    private record Body(string Name);
Body is not used, let's delete this class

2024-10-07 12:56 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Drimstarter.ApiGateway.http
> +GET {{ApiGateway_HostAddress}}/cryptopayments/
Should be fixed as well, if the API endpoint path is changed

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService.Tests/Features/CryptoPayments/cryptopayments.proto
> +option csharp_namespace = "Drimstarter.BlockchainService";
"Drimstarter.BlockchainService.Client" namespace should be used for a client

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Database/BlockchainDbContext.cs
> +            category.HasKey(c => c.AddressId);
`address`, not `category`

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Domain/Address.cs
> +    public required string UserId { get; init; }
Let's add `string Address` to store the generated Bitcoin address

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Errors/CryptoPaymentsValidationErrors.cs
> +    private const string Prefix = "cryptopayments:validation:";
I propose to separate words and use `crypto_payments` instead of `cryptopayments`

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +                UserId = Guid.NewGuid().ToString(),
Let's generate a random string and assign `Address` here too

2024-10-07 12:56 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +            return new() { Address = address.AddressId.ToString() };
I propose to return not `AddressId`, but `Address`

2024-11-03 15:08 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Program.cs
> +// TODO: uncomment after resolving problem with BlockchainService.Client generation
fixed

2024-11-03 15:08 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +        private const string Path = "/cryptopayments";
fixed

2024-11-03 15:09 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Models/DepositAddressModel.cs
> +public record DepositAddressModel(string AddressId);
renamed

2024-11-03 15:13 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Clients/BlockchainService/cryptopayments.proto
> +  string user = 1;
renamed

2024-11-03 15:17 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +                return TypedResults.Created($"{Path}/{depositAddress.AddressId}", depositAddress);
fixed

2024-11-03 15:20 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Database/BlockchainDbContext.cs
> +            category.HasKey(c => c.AddressId);
fixed

2024-11-03 15:22 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Domain/Address.cs
> +    public required string UserId { get; init; }
added BitcoinAddress since `Address` cannot be added (member cannot be same name as type error)

2024-11-03 15:22 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Errors/CryptoPaymentsValidationErrors.cs
> +    private const string Prefix = "cryptopayments:validation:";
fixed

2024-11-03 15:28 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +                UserId = Guid.NewGuid().ToString(),
added `NBitcoin` library, generated BTC address and assigned it to `BitcoinAddress`

2024-11-03 15:31 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +    private record Body(string Name);
I was thinking of using Name as parameter of userId but did not come up with proper way.
In general my view is to get UserId prop from user claims. until that moment, we could pass value for UserId as name in request body. what do you think?

2024-11-03 15:33 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Drimstarter.ApiGateway.http
> +GET {{ApiGateway_HostAddress}}/cryptopayments/
fixed

2024-11-03 15:36 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +            return new() { Address = address.AddressId.ToString() };
fixed. returning `BitcoinAddress`

2024-11-03 15:37 UTC, Kydyralin commented on backend/Services/BlockchainService/Drimstarter.BlockchainService.Tests/Features/CryptoPayments/cryptopayments.proto
> +option csharp_namespace = "Drimstarter.BlockchainService";
fixed

2024-11-03 15:37 UTC, Kydyralin commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +    private record Body(string Name);
removed body

2024-11-04 05:06 UTC, mitro commented on backend/Api/ApiGateway/Drimstarter.ApiGateway/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +    private record Body(string Name);
Let's hardcode UserId for now (right as you did). We'll fix it by using UserId from JWT claims later

2024-11-04 05:32 UTC, mitro requested changes

2024-11-04 05:32 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService.Tests/Features/CryptoPayments/cryptopayments.proto
> +  string user = 1;
It should also be renamed from `user` to `userId`. We currently duplicate proto files, which is an inconvenience. We'll find a solution to remove the duplication later.

2024-11-04 05:32 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Database/BlockchainDbContext.cs
> +            address.HasKey(c => c.AddressId);
Let's map all properties explicitly as in `ProjectDbContext.` With this approach, you can provide MaxLength for BitcoinAddress and create the necessary indices.

2024-11-04 05:32 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Domain/Address.cs
> +    public long AddressId { get; set; }
Let's use `Id` to be consistent with other domain entities.

2024-11-04 05:32 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Domain/Address.cs
> +public class Address
<img width="574" alt="image" src="https://github.com/user-attachments/assets/cd9dcdbe-1dd4-4b91-9acb-0f5f185a77e9">

Rider shows that there are issues with this class:

* `set`s can be replaced with `init`s
* `BitcoinAddress` is a non-nullable property, but it can remain uninitialized, a nullability check violation. Let's make it `required` as `UserId`

I noticed the domain entity `Category` I created in ProjectService has similar issues. I will fix it, too.

P.S. I propose to pay attention to Rider or ReSharper warnings and fix them. If you use VS, I don't know if it has such warnings

2024-11-04 05:32 UTC, mitro commented on backend/Services/BlockchainService/Drimstarter.BlockchainService/Features/CryptoPayments/Requests/GetDepositAddress.cs
> +            var bitcoinAddress = new Key().PubKey.GetAddress(ScriptPubKeyType.Legacy, Network.Main).ToString();
Let's use `ScriptPubKeyType.Segwit` instead of `ScriptPubKeyType.Legacy`. You'll learn the difference later

2024-11-10 06:13 UTC, mitro approved these changes

2024-11-10 10:14 UTC, merged